repository: ENC[AES256_GCM,data:vxzh/CNYUr87lSl2SIl6cIdCasyML95JncQgyLN+J43Ib1LcNMdQC5oh1vlLf0+MT4RCc3N56uVECUp2sq/ZBw==,iv:cmls8n1HVQ1drwIAeDtb0ulZe/GydMbPUXzN+O8Byv8=,tag:pdRcFqkyLnD5pwUKC6EFAA==,type:str]
bucket_name: ENC[AES256_GCM,data:QOAsoWE8a1lgUkQSA25Ko1yFi3ql5nIVUBXzxR0=,iv:TcpUaELkOGvJwBi2RIUy4UBdvJLYinrkX/UXB0BKaQ0=,tag:wrwyUwXIPIxiuc0LubA9GA==,type:str]
restic_password: ENC[AES256_GCM,data:50xZH2b1vtpIbG366zGtTzI=,iv:V2rLh3ASYBSI904j87LPUzU87pi6/OyYiuPGWjSpRkQ=,tag:TMd6kmH86mQUE1Htww1YpQ==,type:str]
access_key_id: ENC[AES256_GCM,data:Cv2IT1zL7rPVBK32Kz0iPRQLesI=,iv:WK9V8W+xsKtcyaiK4f6gpstXo7eiZUakuDTJSXV1m9Y=,tag:5x2INf1lCQd1SqQeqnSSgA==,type:str]
secret_access_key: ENC[AES256_GCM,data:c5lvqlxhShGkLuO8G/YsqHJ2jT2+ZVzEuxLn/tATOgju79FvTUA7Mw==,iv:2+TPgYcAuy2lIwHRdzGNlQwI/RTca5UYT9BKgbBToYk=,tag:hQiLzdXA6lcb51ENgCPBrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYXVQNkIrNWdJQnhFcGFi
            clJrNWhZVXZTZklKTVd5bVZTdzJuN2twNG5RCk50ampPZENGbUxQU2dVZkFqTEcx
            em52M0sxYVg5ODkxMU1tQUgrdktCaU0KLS0tIFFVZENENVNBZm9pRlY2Q2dHTU1E
            OEFzVkEwR2srU0xVQXUxMk9MNTFaRG8Kk7ZvyYSJvZSXuw4lRv/6raIQe/yIg7lU
            7CyAP8pIzBhhWqP3Kbo6U8UqER2RofrRtM4NyORPYwANJOBRT1PO4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T23:48:15Z"
    mac: ENC[AES256_GCM,data:yx+fdhTehfO9+agWBP7qwaQz4cBFhYvMFZojCwzIlDzAYLlrss7eNqLB2vG533rq9hRQpbs3TEeUP7k2Lcqe+k331Qfj8fa503k9bbx+MMVayWyOPnCL+xoSwEUAovduLXg4ynpZLz3MNYXlK2fWtU7XK36Yj6PTIPEymZG/sNg=,iv:fyvRH5hIUTdwq5oo6C95q1wBRHPpv71R2oLoB5M2xUY=,tag:uwvfT3Soct/vZg4HKBDH+A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
