repository: ENC[AES256_GCM,data:LLCQWogy9UTSmMJ6H+mK/JhyfcX760sW5zTQhfGLDrvf9jWP1kRdxW+6E7j5tppiTWWY6gAPKheOd/+yLnCY1Q==,iv:UJI3cYf49BGVkc/4vylRDSqlf/IM/LgpE91TrsIgoyE=,tag:jcsb5HKTNHaEvEPVgbK9VQ==,type:str]
bucket_name: ENC[AES256_GCM,data:WdeigBw65p0K7bGC0iIZbRvdhttnUUgK0WRgB6g=,iv:qfawHhq49Cddhh+066ltwSOMTf7+AyrzDK18F3MlH8c=,tag:fhTvr7WRStPS7Bk8p1qNRw==,type:str]
restic_password: ENC[AES256_GCM,data:0MQVA9TtVAqZMjxzfsip+qI=,iv:SGxr6xQx15NoGV472O/IZriuV+IohYiPzvrwp3Jl8EU=,tag:4yTENhCDABSwLbgSgGR/2A==,type:str]
access_key_id: ENC[AES256_GCM,data:Nikhpzan4VYgeXDmWQ7ZoD6hs3U=,iv:ST9Zb1pN2Ak/r84JTt/7FOlFIWTWugurqKp1EV0q6kc=,tag:IhwjAv+WcVneW1ztYVMbrw==,type:str]
secret_access_key: ENC[AES256_GCM,data:DiPnjl3UHsmAH1r+R9/nWZP3Gi0xXApGZpADmjOqR9bOkYBr3klSNA==,iv:Sv9fcTPXCoJQeN/qvrKVDp+kaZjoz10DLXwGKu/9mjQ=,tag:tb7y1LovRT7Rqx1Vmmcj3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd1NtZ3R6RE9LQ0E1T2dD
            TTMxTjlPWTBPUU15MHE5NllWV2NmdVpKUVVjCjFCckl3N2xla3hnNldJNFpkZWJk
            QVY0ZW1hTnNmejdXY011STJtS3hRaTQKLS0tIFlIZWo5YUJnWkYwcGFsNVZzQldX
            L21HV2FNVHhyVGdpSFJWdm1DQ2tzdzgKdfy7mcO0XW7siXl9YxGZmvKS3IeLwaLb
            1c3S3HeVNr8y6Fu40RQSO+x+1yx7TwFt/MLuw66d6f3Ne37O5pN0Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T06:19:35Z"
    mac: ENC[AES256_GCM,data:M7wLotyeQydHY6fC/zANRjpoffvQMiEoQzU4PkyQfHvyxqSzct+WwVirQhS5iGouRxbCOePabd8I36E4K/XmrgaCPu8EDYFgjO1h8sVeSsWBt+SvSumiJ67PyP3LTk44mUtF/g4gYYFC4azPmq4bBMlh2FBC1O+XRH7P37BhqmI=,iv:fRu9uRgUB05gjGHDsA4D2j5qkZLldMN5z87WWCXZDg0=,tag:GyRHaZmEoePBQ8poSYH7ew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
