apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  namespace: satisfactory
  labels:
    app: satisfactory
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: api
      port: 7777
      protocol: TCP
      targetPort: 7777
      nodePort: 32171
    - name: game
      port: 7777
      protocol: UDP
      targetPort: 7777
      nodePort: 32171
    - name: messaging
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: satisfactory