apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: teamspeak-route-tcp
  namespace: teamspeak
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: HostSNI(`teamspeak.noodles.quest`)
      services:
        - name: teamspeak-service
          port: 30033
          nativeLB: true
        - name: teamspeak-service
          port: 10080
          nativeLB: true
  tls:
    secretName: noodles-quest-prod-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: teamspeak-route-udp
  namespace: teamspeak
spec:
  routes:
    - services:
        - name: teamspeak-service
          port: 9987
          nativeLB: true