{{- $files := .Files }}
{{- $path := "../../../.secrets/github.yaml"}}
{{- $secretData := $files.Get $path | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: foundry
type: Opaque
data:
{{- range $name, $secret := ($secretData) }}
  {{ $name }}: {{ $secret | b64enc }}
{{- end }}
