apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: foundry
spec:
  acme:
    email: brookeporter13@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector: {}
        dns01:
          cloudflare:
            email: brookeporter13@gmail.com
            apiKeySecretRef:
              name: cloudflare
              key: global-api-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-cert-noodles-quest
  namespace: foundry
spec:
  commonName: noodles.quest
  dnsNames:
    - '*.noodles.quest'
    - noodles.quest
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  secretName: noodles-quest-prod-tls
