apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: foundry
  namespace: foundry
spec:
  selector:
    matchLabels:
      app: foundry
  replicas: 1
  template:
    metadata:
      labels:
        app: foundry
    spec:
      containers:
        - name: foundry
          image: docker.io/mephalrith/foundry-server:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 30000
          volumeMounts:
            - mountPath: "/foundrydata"
              name: foundry-pv-storage
      volumes:
        - name: foundry-pv-storage
          persistentVolumeClaim:
            claimName: foundry-pvc