apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-redirect
  namespace: foundry
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service
  namespace: foundry
spec:
  weighted:
    services:
      - name: service
        namespace: foundry
        port: 80
        weight: 1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route
  namespace: foundry
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`foundry.noodles.quest`)
      kind: Rule
      services:
        - name: traefik-service
          namespace: foundry
          kind: TraefikService
      middlewares:
        - name: secure-redirect
  tls:
    secretName: noodles-quest-prod-tls