apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: foundry
spec:
  selector:
    app: foundry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30000
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service
  namespace: foundry
spec:
  weighted:
    services:
      - name: service
        namespace: foundry
        port: 80
        weight: 1