apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enshrouded
  namespace: argocd
spec:
  project: games-project
  sources:
    - repoURL: https://github.com/noodles-org/Noodles
      targetRevision: HEAD
      path: gameserver_deployment/infra/enshrouded
  destination:
    name: games-context
    namespace: enshrouded
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: satisfactory
  namespace: argocd
spec:
  project: games-project
  source:
    repoURL: https://github.com/noodles-org/Noodles
    targetRevision: HEAD
    path: gameserver_deployment/infra/satisfactory
  destination:
    name: games-context
    namespace: satisfactory
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soba
  namespace: argocd
spec:
  project: games-project
  source:
    repoURL: https://github.com/noodles-org/Noodles
    targetRevision: HEAD
    path: gameserver_deployment/infra/soba
  destination:
    name: games-context
    namespace: soba
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valheim
  namespace: argocd
spec:
  project: games-project
  source:
    repoURL: https://github.com/noodles-org/Noodles
    targetRevision: HEAD
    path: gameserver_deployment/infra/valheim
  destination:
    name: games-context
    namespace: valheim
