apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: grafana
spec:
  routes:
    - match: Host(`noodles.local`) && PathPrefix(`/grafana`)
      kind: Rule
      services:
        - name: traefik-service
          kind: TraefikService
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress-route
  namespace: grafana
spec:
  routes:
    - match: PathPrefix(`/metrics`)
      kind: Rule
      services:
        - name: prometheus@internal
          kind: TraefikService
